# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  build:
    cmds:
      - go build -o minitor main.go
  lint:
    cmds:
      - golangci-lint run
  test:
    cmds:
      - go test ./...
  release-snapshot:
    cmds:
      - goreleaser release --snapshot --clean